export const lightColor = {
  white: '#ffffff',
  greyBackground: '#F4F6F6',
  gold: '#F4D03F',
  lightGrey: '#BDC3C7',
  purple: '#3e44aa',
  lightBlue: '#a1dbf5',
  red: 'red',
  black: 'black',
  pink: '#f76269',
  darkGrey: '#939499',
  loginInputGrey: '#E5E7E9',
  cartGrey: '#B2BABB',
  xColor: '#3e44aa',
  eColor: '#a1dbf5',
  shadowWhite: 'white',
  shadowGrey: 'grey',
  filterColor: 'white',
  filterText: 'black',
};
